### ISSUE TITLE
Bubbles on front page appear in front of images

### ISSUE THREAD

**Issue by MasterObvious** [hackcambridge/hc2020-prototype#51]
![IMG_2430](https://user-images.githubusercontent.com/13217875/67583925-78eac780-f744-11e9-9629-9051c8c21f2f.jpg)

**Comment by varadpoddar** [comment]
#53 PR addresses the issue but this seems to be a work in progress. Please consider closing this issue.

For a local development fix, you can add `z-index:2` to your  `&.section-cam-bg::before`  class . 

Full Code : 

```scss
.static-section {
    &::before {
        z-index: -2;
        background: #f8f8ff;
    }

    &.section-blue::before {
        background: #0F2027;
    }

    &.section-cam-bg::before {
        z-index:2;
        background-image: url(https://miro.medium.com/max/12000/1*1SnGVpXWAyOyMpjbsJrPDA.jpeg);
        background-repeat: no-repeat;
        background-position: center center;
        background-size: cover;
        background-attachment: fixed;
        background-color: black;
    }

    .container {
        min-height: calc(var(--hero-diagonal-offset));
    }
}
```
